apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: spaceforces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: frontend
        image: idrisselabidi/spaceforces:frontend-devops-3.0.0
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://spaceforces.com/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m" 